services:
  - type: web
    name: ai-resume-assistant
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PROVIDER
        value: openai
      - key: PORT
        value: 8080
      - key: OPENAI_API_KEY
        scope: project
